### ISSUE TITLE
32-bit ASN Notation Conversion

### ISSUE THREAD

**Issue by mattmiller87** [nautobot/nautobot-plugin-bgp-models#118] opened 2023-08-04 16:30 UTC
### Environment
* Nautobot version: 1.5.0
* nautobot-bgp-models version:  0.7.1

### Proposed Functionality
 **32-bit ASN notations.** Nautobot should be able to read and convert ASN between AS plain and AS dot notations.  

### Use Case
This enables human readable ASNs.

**Comment by mzbroch** [comment] 2023-08-10 11:11
Duplicate of #29

**Closed by mzbroch** 2023-08-10 11:11 UTC
