### ISSUE TITLE
Provide address family mapping for peering

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot-plugin-bgp-models#134] opened 2023-09-26 13:23 UTC
### Environment
* Nautobot version:  1.6.2
* nautobot-bgp-models version:  latest

### Proposed Functionality

Allow for peerings to be associated with any number of address family and VRF tuples.

### Use Case

Example:

Router 1 may peer with Router 2 for address families IPv4 and IPv6 in the VRF Y and at the same time peer with Router 3 for only address family IPv4 in the VRF X and IPv6 in the VRF Z.

### Implementation Proposal

We might want to provide a many to many field on the `Peering` model to the VRF model with a custom through model that allows for address families to be associated.

**Comment by mzbroch** [comment] 2023-09-26 13:37
This is duplicate of #26 and implemented in #132

**Closed by mzbroch** 2023-09-26 13:37 UTC
